[package]
name = "ilmarien"
version = "0.1.0"
authors = ["Filip Øskar Przybycień <filip.oskar@zohomail.eu>"]
edition = "2018"

[dependencies]
log = "0.4.14"
pretty_env_logger = "0.4.0"

geo = "0.18.0"
geo-booleanop = { git = "https://github.com/21re/rust-geo-booleanop" }
geo-types = "0.7.2"
geo-svg = "0.5.0"
tiff = "0.7"
svg = "0.10.0"
noise = "0.7"
splines = "4.0.0"

[dev-dependencies]
float_eq = "0.6"
